name: ai-azure-c1
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - attrs=21.4.0
  - azure-common=1.1.27
  - azure-storage-blob=12.9.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - conda=4.9.2
  - conda-build=3.18.11
  - conda-package-handling=1.8.1
  - conda-verify=3.4.2
  - cryptography=3.4.8
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.2.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - filelock=3.6.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.3.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - icu=58.2
  - idna=3.3
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib_resources=5.2.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isodate=0.6.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyterlab=2.1.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - lcms2=2.12
  - libarchive=3.4.2
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblief=0.11.5
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - msrest=0.6.21
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - oauthlib=3.2.0
  - olefile=0.46
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.2.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pkginfo=1.5.0.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.11.5
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.1
  - python-fastjsonschema=2.15.1
  - python-libarchive-c=2.9
  - pytz=2021.3
  - pywavelets=1.3.0
  - pyyaml=5.3.1
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - ripgrep=12.1.1=0
  - ruamel_yaml=0.15.100
  - scikit-image=0.16.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.10.1
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - anyio==3.6.1
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - azure-ai-formrecognizer==3.1.1
      - azure-cognitiveservices-vision-computervision==0.9.0
      - azure-cognitiveservices-vision-customvision==3.1.0
      - azure-cognitiveservices-vision-face==0.5.0
      - azure-core==1.15.0
      - babel==2.10.1
      - jinja2==3.1.2
      - jupyter-console==6.1.0
      - jupyter-core==4.6.3
      - jupyter-server==1.15.6
      - jupyterlab-server==2.14.0
      - python-dotenv==0.15.0
      - sniffio==1.2.0
      - video-indexer==0.1.8
      - websocket-client==1.3.2
